### ISSUE TITLE
Issue with the version 1.0.0b900 of the integration

### ISSUE THREAD

**Issue by grayve** [py-smart-gardena/hass-gardena-smart-system#116]
Hello,

I believe you are working on it but maybe you need some additional logs. Here are mine as the integration is not working since the upgrade of today (the two)
```
Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:44
Integration: Gardena Smart System integration ([documentation](https://github.com/py-smart-gardena/hass-gardena-smart-system), [issues](https://github.com/py-smart-gardena/hass-gardena-smart-system/issues))
First occurred: 17:22:27 (1 occurrences)
Last logged: 17:22:27
Error setting up entry for gardena_smart_system

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 44, in async_setup_entry
    client_secret=entry.data[CONF_CLIENT_SECRET],
KeyError: 'client_secret'
```

**Comment by grm** [comment]
Hello,

The authentication method has changed and thus the integration need to be reconfigured.

The easiest way to do so i think is by uninstalling it and reinstalling it !
Please let me know if it works

Grm

**Comment by grayve** [comment]
ok thanks work perfectly.

**Comment by kingzize** [comment]
I had the same problem. Perhaps the authors of this integration should provide some more information about breaking changes in the changelogs.

**Comment by grm** [comment]
Hello ! 

I hope the integration works well now.

I updated the README.md, but the info.md (file used by hacs to display info about the integration) was not updated accordingly. I just updated the info.md so it should be fine

Grm

**Comment by grm** [comment]
Hello,

Have you tried uninstalling and reinstalling the integration  ?
