### ISSUE TITLE
Problem to login with Version 1.0.0-0 b901

### ISSUE THREAD

**Issue by kommis** [py-smart-gardena/hass-gardena-smart-system#126]
Hello,

i have a Problem with the login.

Here is the log:

Logger: custom_components.gardena_smart_system
Source: custom_components/gardena_smart_system/__init__.py:88
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 9. Juli 2022, 10:23:56 (1 occurrences)
Last logged: 9. Juli 2022, 10:23:56

No locations found

Second error:

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:84
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 9. Juli 2022, 10:34:17 (1 occurrences)
Last logged: 9. Juli 2022, 10:34:17

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 48, in async_setup_entry
    await gardena_system.start()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 84, in start
    await self.smart_system.authenticate()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 69, in authenticate
    self.token = await self.client.fetch_token(
  File "/usr/local/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 131, in _fetch_token
    return self.parse_response_token(resp.json())
  File "/usr/local/lib/python3.9/site-packages/authlib/oauth2/client.py", line 380, in parse_response_token
    self.handle_error(error, description)
  File "/usr/local/lib/python3.9/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 80, in handle_error
    raise OAuthError(error_type, error_description)
authlib.integrations.base_client.errors.OAuthError: invalid_client: Client not found

Can you help me to solve the Problem? Thanks.

best regards

**Comment by grm** [comment]
Hello,

I think you shoudl recreate the application and reinstall everything (credentials have changed).
It seems the client id your provided (in the first line of the configuration part) is wrong.

**Comment by Tomm206** [comment]
Hello,

I have propably the same problem. I can't login to Gardena API after upgrade. Intergation in HA shows: Failed to set up and same log error as mentioned above. Maybe stupid question but could you please tell me how to recreate the application and reinstall everything? 

Thank you.

**Comment by kommis** [comment]
Hello,

unfortunately I still haven't fixed the problem. I uninstalled the application and re-downloaded and installed it via HACS. Unfortunately I got the same feedback again. Here are the screenshots again.
![grafik](https://user-images.githubusercontent.com/95351671/179738011-57ff168d-d266-4534-a2a7-03ba7abf0652.png)
![grafik](https://user-images.githubusercontent.com/95351671/179738058-7329b6eb-f62e-4466-ab9c-9f1eb7de609b.png)

**Comment by grm** [comment]
@Tomm206 You can go to settings in your home assistant and remove the gardena integration.
Than you add it again and follow the installation.

You should have a location. You granted access to your application to all scopes when you created it  ?

**Comment by kommis** [comment]
> 

Hello,

where can I prove this:

`You granted access to your application to all scopes when you created it ?`

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
