### ISSUE TITLE
ERROR (MainThread) [gardena.smart_system] 429 : Limit Exceeded

### ISSUE THREAD

**Issue by frankvandenhurk** [py-smart-gardena/hass-gardena-smart-system#127]
Every time I restart my HA, i get the following error and the intergartion is not working:

```
2022-07-16 08:56:37 ERROR (MainThread) [gardena.smart_system] 429 : Limit Exceeded
2022-07-16 08:56:37 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 48, in async_setup_entry
    await gardena_system.start()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 85, in start
    await self.smart_system.update_locations()
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 142, in update_locations
    response_data = await self.__call_smart_system_get(
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 137, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 128, in __response_has_errors
    raise Exception(msg)
Exception: Limit Exceeded
```

When I re-enter my credentials it works perfectly, but after a restart it is broken again.

**Comment by thecem** [comment]
Yes the 5 min start timeout in HA is regarding the Gardena integration, with deactivated Gardena 45 sec start, with Gardena aktive 5:45 min…

**Comment by grm** [comment]
Hum,

I am not sure it is related to the statup time.
The error 429 is sent from Gardena.
Could you try to recreate completely the app in the gardena website and reconfigure everything in home assistant afterwards please ?

**Comment by browetd** [comment]
I have the same error message... even with the previous version (0b901 after downgrading from 0b902)... 

So what I did, I went to husqvarna development portal, and renewed the application secret (I did not create a new application, just used the existing one) ... remove the integration from HA (without removing it from HACS), add the integration... enter the old application key and new application secret, and it worked for me (I restarted home assistant without problem)...How it will last, now that's the question as I saw on some blogs that the problem appeared again some time after...  but keep finger crossed...

So this new version for me fixed so far three problems: this one #127 (error 429), the bootstrap issue and the issue #119...

Thanks!!!

**Comment by grm** [comment]
I don't really understand why this happens, i'll try to think about it asap :)

**Comment by nanosonde** [comment]
Maybe related: https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/121#issuecomment-1190603417

**Comment by grm** [comment]
Hello, thanks to the PR of @nanosonde , e have an edge case were when we have a 429 error, the websocket should try again to connect.

I also changed the ping interval from 20 seconds (default value) to 150 seconds as recommended by the husqvarna documentation.
Hopefully, these pings were why we were exceeding the quota per application.

If you could try the b905 version please ?

Thanks

**Comment by grm** [comment]
I released a b906 version which includes a backoff mechanism in case of error connecting to gardena API.

**Comment by frankvandenhurk** [comment]
Upgraded to this ne version and re-created the application in the husqvarna developer portal. So far so good, no more errors. Thank you for your effort!

**Comment by frankvandenhurk** [comment]
Unfortunately, it wasn't fixed, no more data for me:

```
2022-07-23 11:35:36 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 0.6s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-23 11:35:36 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 0.3s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-23 11:35:37 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 1.0s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-23 13:35:48 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 0.9s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-23 23:36:42 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 0.8s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-23 23:36:43 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 1.0s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:36:54 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 0.7s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:36:55 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 1.9s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:36:57 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 1.9s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:36:59 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 1.3s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:37:01 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 11.5s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:37:12 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 16.6s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:37:29 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 60.5s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:38:30 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 101.6s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 01:40:11 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 112.6s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 03:42:14 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 0.4s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 03:42:15 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 1.8s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 03:42:17 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 3.8s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 03:42:21 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 3.5s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 03:42:24 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 7.8s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
2022-07-24 03:42:32 INFO (MainThread) [gardena.smart_system] Backing off __get_ws_url(...) for 27.0s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429)
--
2022-07-24 07:43:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 185, in start_ws
    ws_url = await self.__get_ws_url(location)
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 209, in __get_ws_url
    r = await self.client.post(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1842, in post

```

**Comment by loopway** [comment]
same issue here. removed integration from ha, updated to latest 1.0.0-0b907, restarted ha and tried to add integration again.

```
2022-07-28 23:56:40 ERROR (MainThread) [gardena.smart_system] 429 : Limit Exceeded
2022-07-28 23:56:40 INFO (MainThread) [gardena.smart_system] Backing off __call_smart_system_get(...) for 0.9s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://httpstatuses.com/429)
2022-07-28 23:56:41 ERROR (MainThread) [gardena.smart_system] 429 : Limit Exceeded
2022-07-28 23:56:41 INFO (MainThread) [gardena.smart_system] Backing off __call_smart_system_get(...) for 1.8s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://httpstatuses.com/429)
2022-07-28 23:56:43 ERROR (MainThread) [gardena.smart_system] 429 : Limit Exceeded
2022-07-28 23:56:43 INFO (MainThread) [gardena.smart_system] Backing off __call_smart_system_get(...) for 2.9s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://httpstatuses.com/429)
2022-07-28 23:56:46 ERROR (MainThread) [gardena.smart_system] 429 : Limit Exceeded
2022-07-28 23:56:46 INFO (MainThread) [gardena.smart_system] Backing off __call_smart_system_get(...) for 0.2s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://httpstatuses.com/429)
2022-07-28 23:56:47 ERROR (MainThread) [gardena.smart_system] 429 : Limit Exceeded
2022-07-28 23:56:47 INFO (MainThread) [gardena.smart_system] Backing off __call_smart_system_get(...) for 15.2s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://httpstatuses.com/429)
2022-07-28 23:57:02 ERROR (MainThread) [gardena.smart_system] 429 : Limit Exceeded
2022-07-28 23:57:02 INFO (MainThread) [gardena.smart_system] Backing off __call_smart_system_get(...) for 30.3s (httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://httpstatuses.com/429)
```

**Comment by loopway** [comment]
Just a quick update: After a few days I have added the integration again, and since then, even after updating to the latest home assistant version, the integration has been working without hiccups! 🤞

**Comment by mash727** [comment]
Agree seems to work well and is stable. Great work thanks

loopway ***@***.***> schrieb am So., 14. Aug. 2022, 23:40:

**Comment by frankvandenhurk** [comment]
some here, looks stable, tnx!
