### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by tomdevos2401** [py-smart-gardena/hass-gardena-smart-system#133]
hi, i have the following error when using the smart gardena integration:
thanks for having a look at it.

  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 688, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 76, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/switch/device_action.py", line 25, in async_call_action_from_config
    await toggle_entity.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/toggle_entity.py", line 128, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 984, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/switch.py", line 144, in turn_on
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/gardena/devices/water_control.py", line 34, in start_seconds_to_override
    await self.location.smart_system.call_smart_system_service(self.valve_id, data)
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 97, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
KeyError: 'errors'

**Comment by tomdevos2401** [comment]
version 1.0.0-0b904, jus to be complete

**Comment by mrtobs1** [comment]
hi, first: i loved this integration very much! 

but I have similar errors with the same version 1.0.0-0b904. any help would be great. thank you very much!

`Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
    await gardena_system.start()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 95, in start
    await self.smart_system.update_devices(location)
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 152, in update_devices
    response_data = await self.__call_smart_system_get(
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 133, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 124, in __response_has_errors
    raise Exception(msg)
Exception: Limit Exceeded`

**Comment by cubybox** [comment]
same here :(

**Comment by MartinKuhl** [comment]
Even after I renewed the application secret and readded the Gardena Integration I get the following error:

`2022-07-20 06:09:45 DEBUG (MainThread) [gardena.smart_system] Websocket url retrieved !
2022-07-20 06:09:50 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 189, in start_ws
r.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 736, in raise_for_status
raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/websocket'
For more information check: https://httpstatuses.com/429`

**Comment by MartinKuhl** [comment]
is this error connected to the one above?
`Logger: homeassistant.components.automation.gartenbewasserung
Source: custom_components/gardena_smart_system/switch.py:144
Integration: Automatisierung ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 20:15:52 (4 occurrences)
Last logged: 20:47:50

Gartenbewässerung: Error executing script. Unexpected error for call_service at pos 3: 'errors'
While executing automation automation.gartenbewasserung
Gartenbewässerung: Error executing script. Unexpected error for call_service at pos 8: 'errors'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 984, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/switch.py", line 144, in turn_on
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/gardena/devices/water_control.py", line 34, in start_seconds_to_override
    await self.location.smart_system.call_smart_system_service(self.valve_id, data)
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 97, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
KeyError: 'errors'`

**Comment by mrtobs1** [comment]
Do you guys have Home Assistant Core Version 2022.7.5? Yesterday I restored my HA-backup from Sunday before updating to Version 2022.7.5. Now I have Version 2022.6.7 and Gardena works without any problems! Maybe this will be solved in future-updates of Home Assistant Core? Has anybody already updated to 2022.7.6?

**Comment by MartinKuhl** [comment]
The homematic ip integration had a similar issue with core 2022.7.x. If I remember correctly the issue was connected with the python version. Here is the related fix: https://github.com/hahn-th/homematicip-rest-api/commit/504c75793d9057ecc05b5990450d411ffc0e05d0 
maybe this helps a little bit.

**Comment by grm** [comment]
Hello,

I just deployed a fix in the beta release that should solve 429 issues hopefully.
Regarding the original ticket issue, i'll have a look at it ASAP !

**Comment by ol3k** [comment]
The newest v906 drops an error:

```
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 13:03:57 (1 occurrences)
Last logged: 13:03:57

Setup failed for custom integration gardena_smart_system: Unable to import component: No module named 'backoff'
```

**Comment by MartinKuhl** [comment]
with the new Update 0b906 I am not able to control the the gardena water control anymore. here is the log entry:
`2022-07-22 19:47:50 ERROR (MainThread) [homeassistant.components.automation.gartenbewasserung] While executing automation automation.gartenbewasserung
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 521, in async_trigger
await self.action_script.async_run(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 984, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/gardena_smart_system/switch.py", line 144, in turn_on
).result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
return self.__get_result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
raise self._exception
File "/usr/local/lib/python3.10/site-packages/gardena/devices/water_control.py", line 34, in start_seconds_to_override
await self.location.smart_system.call_smart_system_service(self.valve_id, data)
File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 104, in call_smart_system_service
raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
KeyError: 'errors'`

**Comment by tomdevos2401** [comment]
same here.

**Comment by Roedandan** [comment]
same issue with smart mower btw

**Comment by tomdevos2401** [comment]
hi @grm,

i am still having the initial issue i posted. I add the log again underneath. thank you so much for looking into this and thank you for all the good work.

Tom

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/nodered/websocket.py", line 82, in websocket_device_action
    await platform.async_call_action_from_config(hass, msg["action"], {}, context)
  File "/usr/src/homeassistant/homeassistant/components/switch/device_action.py", line 25, in async_call_action_from_config
    await toggle_entity.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/toggle_entity.py", line 128, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 984, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/switch.py", line 363, in turn_on
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/gardena/devices/smart_irrigation_control.py", line 58, in start_seconds_to_override
    await self.location.smart_system.call_smart_system_service(valve_id, data)
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 108, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
Exception: 502 : Send Command

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
