### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by sabixx** [py-smart-gardena/hass-gardena-smart-system#135]
most of the time the adapter works great, but sometimes after restart I get an error, restating again helps most of the time. 

I only use the irrigation system of Gardena, no mover or else. 

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:86
Integration: Gardena Smart System integration ([documentation](https://github.com/py-smart-gardena/hass-gardena-smart-system), [issues](https://github.com/py-smart-gardena/hass-gardena-smart-system/issues))
First occurred: 15:30:15 (1 occurrences)
Last logged: 15:30:15
Error setting up entry for gardena_smart_system

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
    await gardena_system.start()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start
    await self.smart_system.update_locations()
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 138, in update_locations
    response_data = await self.__call_smart_system_get(
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 133, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 124, in __response_has_errors
    raise Exception(msg)
Exception: Limit Exceeded

**Comment by xses79** [comment]
Im getting the same..

**Comment by olesk75** [comment]
Same here.

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
