### ISSUE TITLE
Error setting up entry for gardena_smart_system 26. Juli 2022 um 23:10:12 – (FEHLER) Gardena Smart System integration (benutzerdefinierte Integration)

### ISSUE THREAD

**Issue by kussione** [py-smart-gardena/hass-gardena-smart-system#137]
The integration isn´t working anymore and I am not happy about. 
How about all my plants and trees?

**Comment by kussione** [comment]
Is somebody working on this issue?

**Comment by Kratax** [comment]
I have the same issue. Gardenta stopped to work couple of weeks ago (not sure if related to some HA update), I am on the latest version 2022.7.7, in logs the following:

`This error originated from a custom integration.

Logger: custom_components.gardena_smart_system.config_flow
Source: custom_components/gardena_smart_system/config_flow.py:132 
Integration: Gardena Smart System integration (documentation, issues) 
First occurred: 9:10:09 AM (1 occurrences) 
Last logged: 9:10:09 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 132, in try_connection
    smart_system.authenticate()
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 115, in authenticate
    self.token = self.oauth_session.fetch_token(
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 448, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) Unauthorized client: `grant_type` is invalid

`

**Comment by Roedandan** [comment]
version?

**Comment by Kratax** [comment]
Sorry for that, update to the latest version helped. can be closed. Using docker, was not aware of new version. Thanks!

**Comment by kussione** [comment]
Can be closed. Thank you. I reinstalled the integration completely new and I used the application key instead the e-Mail Adresse. Noe it is working again.

**Comment by Ralf1973** [comment]
Hello everyone,
I have also a Problem with this.

Protokolldetails (FEHLER)
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:85
Integration: Gardena Smart System integration ([documentation](https://github.com/py-smart-gardena/hass-gardena-smart-system), [issues](https://github.com/py-smart-gardena/hass-gardena-smart-system/issues))
First occurred: 16:41:43 (1 occurrences)
Last logged: 16:41:43

Error setting up entry for gardena_smart_system

**Comment by Kratax** [comment]
And back with me again…

‘’’
Logger: homeassistant.config_entries
Source: components/netatmo/data_handler.py:164 
First occurred: 9:30:17 PM (1 occurrences) 
Last logged: 9:30:17 PM

Error setting up entry Home Assistant Cloud for netatmo
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('169.254.76.175', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 153, in async_setup_entry
    await data_handler.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 108, in async_setup
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 204, in subscribe
    await self.async_fetch_data(signal_name)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/data_handler.py", line 164, in async_fetch_data
    await self.data[signal_name].async_update()
  File "/usr/local/lib/python3.10/site-packages/pyatmo/camera.py", line 649, in async_update
    await self._async_update_all_camera_urls()
  File "/usr/local/lib/python3.10/site-packages/pyatmo/camera.py", line 659, in _async_update_all_camera_urls
    await self.async_update_camera_urls(camera_id)
  File "/usr/local/lib/python3.10/site-packages/pyatmo/camera.py", line 724, in async_update_camera_urls
    ] = await self._async_check_url(
  File "/usr/local/lib/python3.10/site-packages/pyatmo/camera.py", line 731, in _async_check_url
    resp = await self.auth.async_post_request(url=f"{url}/command/ping")
  File "/usr/local/lib/python3.10/site-packages/pyatmo/auth.py", line 335, in async_post_request
    async with self.websession.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 169.254.76.175:80 ssl:default [Connect call failed ('169.254.76.175', 80)]

‘’’

**Comment by kussione** [comment]
Hello everyone, it‘s solved on my site. 
I changed the login from e-Mail to the Application Key. 
It is working fine since than. 

Stefan


Von meinem iPhone gesendet

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
