### ISSUE TITLE
errors (version 1.0.0-0b906)

### ISSUE THREAD

**Issue by jacquesvzijp** [py-smart-gardena/hass-gardena-smart-system#139]
I am still getting errors. This is the water valve. After re-installing it switched on bit gave below at the switch off call.

Logger: homeassistant.components.automation.gras_sproeien
Source: custom_components/gardena_smart_system/switch.py:150 
Integration: Automation (documentation, issues) 
First occurred: 9:08:43 AM (3 occurrences) 
Last logged: 9:08:43 AM

Gras sproeien: Repeat at step 2: Error executing script. Unexpected error for call_service at pos 6: 'errors'
Gras sproeien: Error executing script. Unexpected error for repeat at pos 2: 'errors'
While executing automation automation.gras_sproeien
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_turn_off
    await self.hass.async_add_executor_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/switch.py", line 150, in turn_off
    ).result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/gardena/devices/water_control.py", line 42, in stop_until_next_task
    await self.location.smart_system.call_smart_system_service(self.valve_id, data)
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 104, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
KeyError: 'errors'

**Comment by Roedandan** [comment]
Experiencing this as well.

**Comment by Roedandan** [comment]
thread #133 is describing the same error i guess

**Comment by jacquesvzijp** [comment]
> thread #133 is describing the same error i guess

**Comment by Roedandan** [comment]
I agree it is a good thing this gets more attention indeed :)

**Comment by grm** [comment]
I'll make a quick test for all my devices asap and check taht everything is bahving s expected.
Sorry for the late answer :)

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
