### ISSUE TITLE
no connect /error after update

### ISSUE THREAD

**Issue by clmalacarne** [py-smart-gardena/hass-gardena-smart-system#141]
After install the newest HACS, Gardena Smart System Integration, HASS OS and HomeAssistant, I've the following error:

It's fatal in this hot Sommer for my plants. I hope, you can help me.

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:45
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 13:37:37 (1 occurrences)
Last logged: 13:37:37

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 45, in async_setup_entry
    client_secret=entry.data[CONF_CLIENT_SECRET],
KeyError: 'client_secret'

**Comment by Roedandan** [comment]
Have you tried renewing your application secret yet? Which version are you on?

**Comment by Roedandan** [comment]
For me, the intergration hung and I solved it by renewing the application secret. But I am kind off a noob myself, so that is all I know :)

**Comment by Roedandan** [comment]
version 1.0.0-0b901 is not the current version, I think version 1.0.0-0b902 is the latest stable version (altough it has prolems), and version 1.0.0-0b907 is the latest beta version, altough that seems to have a critical error as well. I have version 1.0.0-0b906 installed, and it appears to be working fine as long as i restart the server every day (automated this)

**Comment by HAConcept** [comment]
I’ve installed the version 1.0.0-0b906. But with the same result. Gardena is not’works. And I’ve the same log-failure. Is there a way to change the Application Secret without reinstall the HA Integration? I would like do this for next step.

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
