### ISSUE TITLE
'<=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by jlatvala** [py-smart-gardena/hass-gardena-smart-system#157]
HA 2023.3.6

Logger: homeassistant.components.vacuum
Source: helpers/icon.py:16
Integration: Vacuum ([documentation](https://www.home-assistant.io/integrations/vacuum), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+vacuum%22))
First occurred: 13:14:12 (2 occurrences)
Last logged: 13:14:12

Error adding entities for domain vacuum with platform gardena_smart_system
Error while setting up gardena_smart_system platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 717, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 807, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 602, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 224, in state_attributes
    data[ATTR_BATTERY_ICON] = self.battery_icon
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 410, in battery_icon
    return icon_for_battery_level(
  File "/usr/src/homeassistant/homeassistant/helpers/icon.py", line 16, in icon_for_battery_level
    elif battery_level <= 5:
TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
