### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by smoki3** [py-smart-gardena/hass-gardena-smart-system#166]
Hi,

my integration stopped working today. I am on HA 2023.05

I get the following issues in the log:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: gardena.smart_system
Source: custom_components/gardena_smart_system/__init__.py:86
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 14:27:37 (7 occurrences)
Last logged: 14:28:11

403 : {'Message': 'User is not authorized to access this resource with an explicit deny'}
```

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:86
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 14:28:16 (1 occurrences)
Last logged: 14:28:16

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 141, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 131, in __response_has_errors
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://httpstatuses.com/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
    await gardena_system.start()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start
    await self.smart_system.update_locations()
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 146, in update_locations
    response_data = await self.__call_smart_system_get(
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 183, in retry
    await asyncio.sleep(seconds)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

```

**Comment by pduchnovsky** [comment]
Same problem here, 1.0.0 as well as recent 1.0.1 has the same problem.

```
2023-05-03 14:22:06.599 ERROR (MainThread) [gardena.smart_system] 403 : {'Message': 'User is not authorized to access this resource with an explicit deny'}
2023-05-03 14:22:06.600 INFO (MainThread) [gardena.smart_system] Backing off __call_smart_system_get(...) for 3.4s (httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://httpstatuses.com/403)
```

**Comment by mxkissnr** [comment]
Same problem here:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: gardena.smart_system
Source: custom_components/gardena_smart_system/__init__.py:86
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 15:02:03 (10 occurrences)
Last logged: 15:06:34

403 : {'Message': 'User is not authorized to access this resource with an explicit deny'}

**Comment by hegart** [comment]
Same problem here: Home Assistant 2023.3.6 
gardena.smart_system 1.0.1

**Comment by vedette15** [comment]
Same problem here

**Comment by tanderloco** [comment]
Same problem here (HA: 2023.2.2)

**Comment by guennikasse** [comment]
Same problem here
Home Assistant 2023.4.0
OS 10.1

**Comment by sashgithub** [comment]
Hi,

Gardena renew the Portal.
You have to Login to the dev Portal of Gardena and autorize the App to communicate with API. You get the Question by Login.

After that i have deleted the old API cretentials and create new cretentials with New Application Key / Client ID and Application secret / client secret.

At the end i deleted the integration in Home Assistant and Install it New with the New cretentials.

And now it works again in Home Assistant ;-).

Good luck.

**Comment by Reudo** [comment]
Same here. It works again.

**Comment by mxkissnr** [comment]
@sashgithub Thank you it works again.

**Comment by vedette15** [comment]
I cannot get it to work again, what am i doing wrong.......

Do I need to cfreate an new app, and if so what is the redirect url?

**Comment by guennikasse** [comment]
You can use "http://localhost:8080" for redirect url

**Comment by vedette15** [comment]
Tnx!!!!!

**Comment by grm** [comment]
Thanks @sashgithub for the reactivity on solving the issue ! 
Awesome <3

**Comment by Symbiot78** [comment]
fixed by authorizing after login.
deleting the app in HA
setting it up again.
Same secret etc. from developer husqvarna.

**Comment by Robbe-B** [comment]
Same issues, same fix , Thanks !

**Comment by leppa** [comment]
Just a note: I didn't have to create new application. Only went to *[My Applications](https://developer.husqvarnagroup.cloud/applications)* -> *SHOW MORE* on my application -> *CONNECT NEW API* and added all available APIs. After that I simply restarted Home Assistant and everything works again.

**Comment by nopbop** [comment]
> Hi,
> 
> Gardena renew the Portal. You have to Login to the dev Portal of Gardena and autorize the App to communicate with API. You get the Question by Login.
> 
> After that i have deleted the old API cretentials and create new cretentials with New Application Key / Client ID and Application secret / client secret.
> 
> At the end i deleted the integration in Home Assistant and Install it New with the New cretentials.
> 
> And now it works again in Home Assistant ;-).
> 
> Good luck.

Thanks you, this works again for me.

**Comment by Aham330** [comment]
> Same problem here:
> 
> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> 
> Logger: gardena.smart_system Source: custom_components/gardena_smart_system/**init**.py:86 Integration: Gardena Smart System integration (documentation, issues) First occurred: 15:02:03 (10 occurrences) Last logged: 15:06:34
> 
> 403 : {'Message': 'User is not authorized to access this resource with an explicit deny'}

I get the same message. Tried all suggestions but it simple does not work.

**Comment by Reudo** [comment]
> > Same problem here:
> > Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> > Logger: gardena.smart_system Source: custom_components/gardena_smart_system/**init**.py:86 Integration: Gardena Smart System integration (documentation, issues) First occurred: 15:02:03 (10 occurrences) Last logged: 15:06:34
> > 403 : {'Message': 'User is not authorized to access this resource with an explicit deny'}
> 
> I get the same message. Tried all suggestions but it simple does not work.

Are you sure about that? At first I thought adding the new APIs is enough but that didn't work for me.

Delete the Application, click on "NEW APPLICATION" fill out the information and connect the "Authentication API" and "GARDENA smart system API".

After that connect the integration in HA again.

**Comment by Aham330** [comment]
> > > Same problem here:
> > > Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> > > Logger: gardena.smart_system Source: custom_components/gardena_smart_system/**init**.py:86 Integration: Gardena Smart System integration (documentation, issues) First occurred: 15:02:03 (10 occurrences) Last logged: 15:06:34
> > > 403 : {'Message': 'User is not authorized to access this resource with an explicit deny'}
> > 
> > 
> > I get the same message. Tried all suggestions but it simple does not work.
> 
> Are you sure about that? At first I thought adding the new APIs is enough but that didn't work for me.
> 
> Delete the Application, click on "NEW APPLICATION" fill out the information and connect the "Authentication API" and "GARDENA smart system API".
> 
> After that connect the integration in HA again.

Golden tip .TNX got it working.

**Comment by m33ts4k0z** [comment]
Hello.

This seems completely broken at the moment. I tried all the suggestions above but when I enter my credentials, I get this:

```
2023-05-06 20:20:56.299 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gardena_smart_system which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-06 20:30:58.347 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for gardena_smart_system
File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start
2023-05-06 20:33:24.227 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for gardena_smart_system
File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start
2023-05-06 20:36:04.264 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for gardena_smart_system
File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start
2023-05-06 20:40:35.859 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for gardena_smart_system
File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start
2023-05-06 20:41:34.178 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for gardena_smart_system
File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start
```

**Comment by Reudo** [comment]
> m33ts4k0z

Have you tried reinstalling the Gardena HACS Integration or maybe there is an update available for you?
Looks like everyone (?) else got it working again.

**Comment by MrBean2016** [comment]
Same problem, "Gardena smart system connection - disconnected". So I just restarted Home Assistant and then it worked again, no need to reconfigure keys. Maybe there is need for some kind of keep-alive or refresh token/connection functionality?
