### ISSUE TITLE
Error setting up web socket

### ISSUE THREAD

**Issue by MadMonkey87** [py-smart-gardena/hass-gardena-smart-system#172]
I've noticed that binary_sensor.gardena_smart_system_connection is often reported as disconnected. I've found the following in the logs, any idea what the problem is?

2023-05-21 20:05:44.780 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration gardena_smart_system which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-21 20:05:55.369 DEBUG (MainThread) [custom_components.gardena_smart_system] Setting up Gardena Smart System component
2023-05-21 20:05:55.370 DEBUG (MainThread) [custom_components.gardena_smart_system] Starting GardenaSmartSystem
2023-05-21 20:05:57.014 DEBUG (MainThread) [custom_components.gardena_smart_system] Using location: My Garden (834c2d20-561b-XXXXXXXXXX....)
2023-05-21 20:05:57.174 DEBUG (MainThread) [custom_components.gardena_smart_system] Starting GardenaSmartSystem websocket
2023-05-21 20:05:57.175 DEBUG (MainThread) [custom_components.gardena_smart_system] Websocket thread launched !
2023-05-21 20:05:57.175 DEBUG (MainThread) [custom_components.gardena_smart_system] Gardena Smart System component setup finished
2023-05-21 20:05:57.183 DEBUG (MainThread) [custom_components.gardena_smart_system.sensor] Adding sensor as sensor [<entity None=50>]
2023-05-21 20:05:57.184 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Adding water control, power socket and smart irrigation control as switch: []
2023-05-21 20:05:57.209 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Adding mower as vacuums: [<entity None=unknown>]
2023-05-21 20:05:57.213 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Running Gardena update
2023-05-21 20:05:57.213 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Mower has state OK
2023-05-21 20:05:57.213 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Getting mower state
2023-05-21 20:05:57.213 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Mower has activity OK_SEARCHING
2023-05-21 20:06:12.621 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 190, in start_ws
    await self.__launch_websocket_loop(ws_url)
  File "/usr/local/lib/python3.10/site-packages/gardena/smart_system.py", line 227, in __launch_websocket_loop
    websocket = await websockets.connect(url, ping_interval=150)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1036, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1418, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
