### ISSUE TITLE
Gardena integration not available/loaded

### ISSUE THREAD

**Issue by Pilot2023** [py-smart-gardena/hass-gardena-smart-system#199]
Dears, 
I recognized a few days ago that the Gardena integration is not available any more. 
Within the integrations its listet as "not loaded" as attached. Reboot or any other action does not show any positive effects...
Is this a common issue temporary or some fault on my side?

Thanks a lot in advance !

BR
Alex

![Gardena not loaded](https://github.com/py-smart-gardena/hass-gardena-smart-system/assets/121667461/1f75f166-0638-47a5-b74a-f82d28fd57a6)

**Comment by grm** [comment]
Hello,

Have you updated to latest version ?

Jérémie

**Comment by Pilot2023** [comment]
Hi, yes I did the updates...BR
-------- Ursprüngliche Nachricht --------Von: Jérémie Klein ***@***.***> Datum: 12.02.24  13:14  (GMT+01:00) An: py-smart-gardena/hass-gardena-smart-system ***@***.***> Cc: Pilot2023 ***@***.***>, Author ***@***.***> Betreff: Re: [py-smart-gardena/hass-gardena-smart-system] Gardena integration not available/loaded (Issue #199) 
Hello,



Have you updated to latest version ?



Jérémie

**Comment by Pilot2023** [comment]
I did another reboot and its working now.Thanks a lot for your quick reply.I thought I did everything I can already. Sometimes its easier as you think  ;)BR Alex
-------- Ursprüngliche Nachricht --------Von: Jérémie Klein ***@***.***> Datum: 12.02.24  13:14  (GMT+01:00) An: py-smart-gardena/hass-gardena-smart-system ***@***.***> Cc: Pilot2023 ***@***.***>, Author ***@***.***> Betreff: Re: [py-smart-gardena/hass-gardena-smart-system] Gardena integration not available/loaded (Issue #199) 
Hello,



Have you updated to latest version ?



Jérémie

**Comment by martinw72** [comment]
you need version 1.1.0 or 1.1.1-rc1

**Comment by clipse2004** [comment]
Hi, unfortunately I have the same problem. I have already tried deleting everything and everything worked again until I restarted. I'm using the latest beta version (1.1.1-rc1), but it's the same problem.

I have also tried to create a new API, unfortunately the same result.

Greetings

**Comment by Ofensepp** [comment]
> Hi, unfortunately I have the same problem. I have already tried deleting everything and everything worked again until I restarted. I'm using the latest beta version (1.1.1-rc1), but it's the same problem.
> 
> I have also tried to create a new API, unfortunately the same result.
> 
> Greetings

I had the same, Clear install, new API, V1.1.1, works one time, after reboot it won‘t work anymore

**Comment by JSamsom72** [comment]
Same behavior here. It seems to me it’s not reliable on restart/reboot HA. Sometimes it works, sometimes not. I am on all latest supported versions.

**Comment by TTLucian** [comment]
Same here. Integration not loaded (failed to set up):
```
Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 01:26:21 (1 occurrences)
Last logged: 01:26:21

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_core/_sockets.py", line 222, in connect_tcp
    await event.wait()
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1613, in wait
    await self._event.wait()
  File "/usr/local/lib/python3.12/asyncio/locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f61af5098b0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with anyio.fail_after(timeout):
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
    await gardena_system.start()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 85, in start
    await self.smart_system.authenticate()
  File "/usr/local/lib/python3.12/site-packages/gardena/smart_system.py", line 80, in authenticate
    self.token_manager.load_from_oauth2_token(await self.client.fetch_token(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 125, in _fetch_token
    resp = await self.post(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1877, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/authlib/integrations/httpx_client/oauth2_client.py", line 90, in request
    return await super().request(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1559, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 370, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

**Comment by bastiaanterhorst** [comment]
Same issue. For me it broke in this way directly after the update to 2024.2.4

**Comment by kizio1000** [comment]
Hi guys. Same here but I found that every time it will not work it is possible to force it to work by disabling integration and then enabling it again. Seams that since last changes in HA there is some issue with vacuums that affects movers too. I am concluding it from fact that my roborock integration does the same and same method helps to get it working.

**Comment by grm** [comment]
There is a new beta release 1.1.1-rc2

can you try ? (i am not sure it will help, but I'll try to have a look after your feedback)

**Comment by TTLucian** [comment]
1.1.1-rc3 seems to be working after one core restart. Needs further testing! Why not implement the reload service for this integration? It's the only one I've encountered so far that doesn't have a reload service!

**Comment by grm** [comment]
Hello,
I am not sure to understand what you are talking about when saying ' reload service'.

Do you have an example ?

**Comment by TTLucian** [comment]
https://community.home-assistant.io/t/wth-is-there-no-reload-integration-service/467191
![Screenshot_2024-03-17-23-58-46-92_c3a231c25ed346e59462e84656a70e50](https://github.com/py-smart-gardena/hass-gardena-smart-system/assets/1855276/090d88aa-1b57-4ff8-ad07-bf75b718dc83)
![Screenshot_2024-03-17-23-58-33-82_c3a231c25ed346e59462e84656a70e50](https://github.com/py-smart-gardena/hass-gardena-smart-system/assets/1855276/376ee855-ed02-48ad-a44a-d03ef3ce297f)
As you can see, the Gardena integration doesn't have a reload option...

**Comment by Doppelkeks** [comment]
I also have this problem after restarting HA, i usally have to disable and enable this integration again.

**Comment by marcoraddatz** [comment]
Even though I cannot contribute much information: I got the same issue that I always need to reload it manually after a restart.

**Comment by jeff1975** [comment]
I got the same issue that I always need to reload it manually after a restart

**Comment by kizio1000** [comment]
After update to RC3 first start of system was ok and each following restart shows that problem is still present

**Comment by bpcrocke** [comment]
Same problem here. Sometimes even restarting does not help. Only creating new API credentials worked. So there also seems to be something wrong with API polling and/or API limits.

**Comment by freddeh** [comment]
> I got the same issue that I always need to reload it manually after a restart

Exactly the same here...

**Comment by Elle4u** [comment]
The same by me, again. Version 1.1.1-rc3 did solve the problem for some time but now the problem came back.
Sometimes its running without problems after restart. Mostly I have to disable/enable the integration manually...

**Comment by somansch** [comment]
I have the same issue and see it after I had (nightly) internet connection interruption (03:47). It seems, that normally this integration or the remote server reconnects each 2 hours?
![image](https://github.com/py-smart-gardena/hass-gardena-smart-system/assets/47367267/eb9cca22-725b-4374-8545-660ceb8f6dcf)

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
