### ISSUE TITLE
Can't use actions in Home Assistant

### ISSUE THREAD

**Issue by sabbatho** [py-smart-gardena/hass-gardena-smart-system#20]
Hi,
I am trying to setup som automations to vacuum.start and vacuum.stop.
But when i try to use the buttons on the entity card i get this error:

Logginformation (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.140165153689232
Source: custom_components/gardena_smart_system/vacuum.py:170
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:29:02 (1 occurrences)
Last logged: 11:29:02

502 : error communicating with the backend
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 370, in async_start
    await self.hass.async_add_executor_job(self.start)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/vacuum.py", line 170, in start
    self._device.start_seconds_to_override(duration)
  File "/usr/local/lib/python3.7/site-packages/gardena/devices/mower.py", line 30, in start_seconds_to_override
    self.smart_system.call_smart_system_service(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 136, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
Exception: 502 : error communicating with the backend
Misslyckades med att anropa tjänsten vacuum/start. 502 : error communicating with the backend

Might there be need for a port forward or something? Does anyone have any idea?
It works from the Gardena app, but not from Home assistant. And i have tried through automations, manual and developer tools. Sensors update fine, it's only sending commands that won't work.

Installed through HACS, and have done all configs according to installation notes.

Hope i have provided what is needed?

Thanks in advance for any help :)

**Comment by grm** [comment]
Could you try the new version 0.1.0 and tell me if it changes something on your side ?

**Comment by sabbatho** [comment]
No more errors with 0.1.0, But i can't do actions live sopt or start. Have tried through the card and buttons, and developer tools. And nothing in the loggs now at all.
Thanks so much :)

**Comment by grm** [comment]
You mean you do not have errors in logs but the commands are not working ?

I just tried on my side and it seems my mower is working. Can you send us
how do you call the actions?

Grm

**Comment by sabbatho** [comment]
I'm sorry for not being clear.
Thats right, i have no errors in log now, and the commands are not working still.

I have tried these buttons:
![image](https://user-images.githubusercontent.com/48513738/83969891-d0eccd80-a8d2-11ea-8ab1-0118071ce7e4.png)

And i have tried this way with both start and stop:
![image](https://user-images.githubusercontent.com/48513738/83969908-ebbf4200-a8d2-11ea-8b08-8f475eb64840.png)

but i get no respons from the mower, i also check the status in the gardena app to be sure but same status there as in Home Assistant.

Of course i have tried stop when the mower is mowing, and i have tried start when the mower is parked and battery is 100%. Just to be clear :)

could i maybe try doin a manual command like a curl to rule out any settings from my part? not sure how it would look like though? Not being very used to sending manual commands.

And as you can see the integration work as for recieving data, just no sending that will work.

**Comment by sabbatho** [comment]
Today as an automation triggered i found this in my logs, strange that i didn't get this when i tried yesterday in my logs:


Logginformation (ERROR)
Logger: homeassistant.components.automation
Source: custom_components/gardena_smart_system/vacuum.py:170
Integration: Automation (documentation, issues)
First occurred: 10:00:01 (1 occurrences)
Last logged: 10:00:01

Sileno_start: Error executing script. Unexpected error for call_service at pos 1: 502 : error communicating with the backend
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 623, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 370, in async_start
    await self.hass.async_add_executor_job(self.start)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/vacuum.py", line 170, in start
    self._device.start_seconds_to_override(duration)
  File "/usr/local/lib/python3.7/site-packages/gardena/devices/mower.py", line 31, in start_seconds_to_override
    self.smart_system.call_smart_system_service(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 155, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
Exception: 502 : error communicating with the backend

**Comment by northpower25** [comment]
@grm @osks any idea?

**Comment by basn** [comment]
I got the exact same issue, if needed for debuging.

**Comment by grm** [comment]
That is really strange, here is what i got in lovelace and working perfectly. 
The error 502 seems to me an issue on the gardena side (and that is something we can't do much).
You have this issue all the time ? or sometimes it works and others not ?

Are you behind a firewall, or have some specific network equipments ?

Grm

**Comment by basn** [comment]
I cant use it at all, i always get the 502 issue.
Seems like both are us are Swedish also, maybe they have something different for us?

Behind a NAT firewal sure, but its proxying 443 to nginx that passes traffic to HA

**Comment by sabbatho** [comment]
@grm, i have a pfsense firewall, Just the Home Assistant portforward for lovelace access.
Have updated everything aswell as of today, Home Assistant is latest 0.111.4 and Gardena Smart System 0.2.0 (through hacs).
Still have the 502 error.

**Comment by grm** [comment]
This is really strange,

Would you mind send me your creds and application key by mail so i give it a try by myself as I can't reproduce it on my side ?

Thx,
Jérémie

**Comment by sabbatho** [comment]
sure @grm

**Comment by basn** [comment]
any updates? or did you not get application key etc?

**Comment by grm** [comment]
Hello everyone,

After discussion with the devs from Gardena, i think we found the issue source. It comes from the handling of the id, where for some mowers id from mowers have a suffix that others do not have. I will try to make an update soon to py-smart-gardena to support this use case !

**Comment by grm** [comment]
Hello,

The Fix has been released into beta version 0.2.1b2.

Could you give it a try please ?

Grm

**Comment by grm** [comment]
The bug has really been fixed in 0.2.1b3 :)

**Comment by sabbatho** [comment]
Confirmed and working!  Thanks @grm for all the time you have put into this :)
