### ISSUE TITLE
Detected blocking call to load_default_certs with args

### ISSUE THREAD

**Issue by andyblac** [py-smart-gardena/hass-gardena-smart-system#228]
error in log.

log:
```
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 10:22:51 (1 occurrences)
Last logged: 10:22:51

Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7fe4b40ea2d0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) in /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/gardena/smart_system.py", line 190, in start_ws await self.__launch_websocket_loop(ws_url) File "/usr/local/lib/python3.12/site-packages/gardena/smart_system.py", line 227, in __launch_websocket_loop websocket = await websockets.connect(url, ping_interval=150) File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 653, in __await_impl__ _transport, protocol = await self._create_connection() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1149, in create_connection transport, protocol = await self._create_connection_transport( File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1173, in _create_connection_transport transport = self._make_ssl_transport( File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 83, in _make_ssl_transport ssl_protocol = sslproto.SSLProtocol( File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 295, in __init__ sslcontext = _create_transport_context( File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 55, in _create_transport_context sslcontext = ssl.create_default_context() File "/usr/local/lib/python3.12/ssl.py", line 713, in create_default_context context.load_default_certs(purpose)
```

**Comment by snfx-johaver** [comment]
+1 same here
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: October 9, 2024 at 23:54:48 (2 occurrences)
Last logged: October 9, 2024 at 23:54:54

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f2ff6b5e7d0>,) inside the event loop by custom integration 'gardena_smart_system' at custom_components/gardena_smart_system/__init__.py, line 86: await self.smart_system.authenticate() (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/py-smart-gardena/hass-gardena-smart-system/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry await gardena_system.start() File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start await self.smart_system.authenticate()
Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f2feb81afd0>,) inside the event loop by custom integration 'phyn' at custom_components/phyn/__init__.py, line 64: await client.mqtt.connect() (offender: /usr/local/lib/python3.12/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/jordanruthe/homeassistant-phyn/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/phyn/__init__.py", line 64, in async_setup_entry await client.mqtt.connect()

**Comment by JoelSnyder** [comment]
Same issue here with both error messages (Detected blocking call to load_verify_locations) and (Detected blocking call to load_default_certs).  However, it seems that this is one of those things that is just "ok, this will slow down your startup" rather than a true error that's going to cause issues.  

Obviously it would be nice if we didn't have stuff in the home-assistant.log file but this doesn't seem to be a thing that's going to really affect actual operations--just slow down startup/restart of the component. 

`2024-11-26 18:27:15.123 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fb124aec450>,) inside the event loop by custom integration 'garden
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations                                                                                                          
Traceback (most recent call last):                                                                                                                                                                                               
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                                                                        
  File "<frozen runpy>", line 88, in _run_code                                                                                                                                                                                   
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>                                                                                                                                                 
    sys.exit(main())                                                                                                                                                                                                             
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main                                                                                                                                                     
    exit_code = runner.run(runtime_conf)                                                                                                                                                                                         
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run                                                                                                                                                        
    return loop.run_until_complete(setup_and_run_hass(runtime_config))                                                                                                                                                           
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete                                                                                                                                       
    self.run_forever()                                                                                                                                                                                                           
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever                                                                                                                                              
    self._run_once()                                                                                                                                                                                                             
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once                                                                                                                                               
    handle._run()                                                                                                                                                                                                                
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run                                                                                                                                                           
    self._context.run(self._callback, *self._args)                                                                                                                                                                               
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component                                                                                                                                       
    result = await _async_setup_component(hass, domain, config)                                                                                                                                                                  
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component                                                                                                                                      
    await asyncio.gather(                                                                                                                                                                                                        
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>                                                                                                                                                   
    create_eager_task(                                                                                                                                                                                                           
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task                                                                                                                                      
    return Task(coro, loop=loop, name=name, eager_start=True)                                                                                                                                                                    
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked                                                                                                                                 
    await self.async_setup(hass, integration=integration)                                                                                                                                                                        
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup                                                                                                                                        
    await self.__async_setup_with_context(hass, integration)                                                                                                                                                                     
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context                                                                                                                         
    result = await component.async_setup_entry(hass, self)                                                                                                                                                                       
  File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry                                                                                                                               
    await gardena_system.start()                                                                                                                                                                                                 
  File "/config/custom_components/gardena_smart_system/__init__.py", line 86, in start                                                                                                                                           
    await self.smart_system.authenticate()                                                                                                                                                                                       
`

and 

`2024-11-26 18:27:16.438 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7fb121960150>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='s
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                               
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                                                                                                        
  File "<frozen runpy>", line 88, in _run_code                                                                                                                                                                                   
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>                                                                                                                                                 
    sys.exit(main())                                                                                                                                                                                                             
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main                                                                                                                                                     
    exit_code = runner.run(runtime_conf)                                                                                                                                                                                         
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run                                                                                                                                                        
    return loop.run_until_complete(setup_and_run_hass(runtime_config))                                                                                                                                                           
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete                                                                                                                                       
    self.run_forever()                                                                                                                                                                                                           
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever                                                                                                                                              
    self._run_once()                                                                                                                                                                                                             
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once                                                                                                                                               
    handle._run()                                                                                                                                                                                                                
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run                                                                                                                                                           
    self._context.run(self._callback, *self._args)                                                                                                                                                                               
  File "/usr/local/lib/python3.12/site-packages/gardena/smart_system.py", line 190, in start_ws                                                                                                                                  
    await self.__launch_websocket_loop(ws_url)                                                                                                                                                                                   
  File "/usr/local/lib/python3.12/site-packages/gardena/smart_system.py", line 227, in __launch_websocket_loop                                                                                                                   
    websocket = await websockets.connect(url, ping_interval=150)                                                                                                                                                                 
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 442, in __await_impl__                                                                                                                       
    self.connection = await self.create_connection()                                                                                                                                                                             
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 368, in create_connection                                                                                                                    
    _, connection = await loop.create_connection(factory, **kwargs)                                                                                                                                                              
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1149, in create_connection                                                                                                                                       
    transport, protocol = await self._create_connection_transport(                                                                                                                                                               
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1173, in _create_connection_transport                                                                                                                            
    transport = self._make_ssl_transport(                                                                                                                                                                                        
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 83, in _make_ssl_transport                                                                                                                                   
    ssl_protocol = sslproto.SSLProtocol(                                                                                                                                                                                         
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 295, in __init__                                                                                                                                                    
    sslcontext = _create_transport_context(                                                                                                                                                                                      
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 55, in _create_transport_context                                                                                                                                    
    sslcontext = ssl.create_default_context()                                                                                                                                                                                    
  File "/usr/local/lib/python3.12/ssl.py", line 713, in create_default_context                                                                                                                                                   
    context.load_default_certs(purpose)                                                                                                                                                                                          
`

**Comment by snfx-johaver** [comment]
same one here.  does seem to slow down .   just updated to last beta 1.1.2 , but is also there in 1.1.1

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 22:20:57 (1 occurrences)
Last logged: 22:20:57

Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fb2e2dac7a0>,) inside the event loop by custom integration 'gardena_smart_system' at custom_components/gardena_smart_system/init.py, line 86: await self.smart_system.authenticate() (offender: /usr/local/lib/python3.13/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/py-smart-gardena/hass-gardena-smart-system/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "", line 198, in _run_module_as_main File "", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/main.py", line 227, in sys.exit(main()) File "/usr/src/homeassistant/homeassistant/main.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 788, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/gardena_smart_system/init.py", line 49, in async_setup_entry await gardena_system.start() File "/config/custom_components/gardena_smart_system/init.py", line 86, in start await self.smart_system.authenticate()

**Comment by grm** [comment]
Should be fixed in the next release :)

**Comment by grm** [comment]
Closing — this was a v1.x issue. The integration has been completely rewritten in v2.x with a new architecture (no more py-smart-gardena dependency, native websocket handling, proper token refresh, LawnMowerEntity support). Please upgrade to v2.x via HACS. If you still experience issues on v2.x, please open a new issue.
