### ISSUE TITLE
Smart Perssure Pump not working

### ISSUE THREAD

**Issue by martinos87** [py-smart-gardena/hass-gardena-smart-system#28]
I own a gardena smart perssure pump and would like to control it using HA.

The issue is that when I press the switch for the pump I get a 502 communication error.
But if I use the gardena app to switch on / off the pump the state is reportet correctly back to HA.

I also have a smart irrigation controller which is working nicely in combination with this integration.

Here is the log:
502 : error communicating with the backend
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 622, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/switch.py", line 142, in turn_on
    self._device.start_seconds_to_override(duration)
  File "/usr/local/lib/python3.7/site-packages/gardena/devices/water_control.py", line 33, in start_seconds_to_override
    self.smart_system.call_smart_system_service(self.id, data)
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 155, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
Exception: 502 : error communicating with the backend

**Comment by schlaubi79** [comment]
I've got the same issue when I try to start my mower; all versions of HA, the gardena plugin as well as mower firmware are on latest release, did not change anything.
Other components like water control are doing well including start and stop.

**Comment by grm** [comment]
Hello The MR has been merged into beat version 0.2.1b2.

Could you give it a try please ?

**Comment by grm** [comment]
I close this issue.
The support has been merged.
If you still have issue, do not hesitate to re-open it.

**Comment by benjycov** [comment]
Hi,

I have the smart pressure pump (and pretty much everything else).

The pressure pump is recognised, however the only entity is 'battery' - which it doesn't have.

Its classed the same as a water control  (which does have a battery), and it doesn't have a valve action. However it does have an action when it is in error state (reset - normally to re-prime the pump).

It would be really useful to see the pumps status particularly for error so some action can be taken (the same as can be done for a mower).

The normal error is problem on suction side - i.e. your water tank is empty and you need to do something else until it rains again - the something else is to reconfigure the smart irrigation system to enable the master valve (which doesn't appear to be exposed by the API) to enable mains water to be used. I suspect this will be manual for now!

**Comment by grm** [comment]
I originally planned to own a pump in order to make somme deeper tests !
Unfortunately, i did not buy one (i have not a qwater tank so it would be pretty useless to me).
If at some point, i find a used one, i may jump .. but for now I can't !

Sorry about that !

**Comment by frathh** [comment]
Thanks for the update anyway, @grm  . Got the same challenge as @benjycov - for me the major benefit of the integration of the pressure pump would be sensor data - how often did it run, how much water went through etc. Anything we could do to help as long as you don‘t own one? Have to admit that that I am rather new to HA though, but happy to help.

**Comment by frathh** [comment]
Any further idea on this? Would really like to get hold of the pump statistics. Thx

**Comment by schnettker** [comment]
is a integration for the pump planned?

**Comment by grm** [comment]
Hello,

sorry for the lag, I am currently working on a solution to fix the issue i have witha. library for a long time.

After that, I may try to work on it !

**Comment by schnettker** [comment]
Thank you for the response!

**Comment by schnettker** [comment]
It is still not working. Do you still try to fix it? Can i help you?

**Comment by grm** [comment]
The original 502 error was fixed back in v0.2.1b2 (2020). The Smart Pressure Pump is exposed by the Gardena API as a standard VALVE/COMMON device — the integration handles these correctly now. For pump-specific statistics or error states, the API v2 doesn't expose dedicated pump data beyond what's available through the standard services. Closing as resolved.
