### ISSUE TITLE
Exception: 502 : error communicating with the backend, when hitting start

### ISSUE THREAD

**Issue by eich0rn** [py-smart-gardena/hass-gardena-smart-system#39]
I can read all Attributes in HA. But when i want to start my Mover the above error shows up.
Environment:
HA Operating System 4.10
Home Assistant Core: 0.113.0
HACS Version: 1.2.2
Gardena Version 0.2.1
Running on a RaspPi 3b

Protokolldetails ( ERROR )
Logger: homeassistant.components.websocket_api.http.connection.1859044208
Source: custom_components/gardena_smart_system/vacuum.py:174
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:19:16 (1 occurrences)
Last logged: 15:19:16

502 : error communicating with the backend
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1250, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1285, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 361, in async_start
    await self.hass.async_add_executor_job(self.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/vacuum.py", line 174, in start
    self._device.start_seconds_to_override(duration)
  File "/usr/local/lib/python3.8/site-packages/gardena/devices/mower.py", line 34, in start_seconds_to_override
    self.smart_system.call_smart_system_service(self.id, data)
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 155, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
Exception: 502 : error communicating with the backend

**Comment by ulfur8149** [comment]
This is probably a bug that has been resolved in the latest version of the gardena library in your homeassistant installation folder. The error message provided from Gardena API is not really clear, but most likely it is the fact that your mower ID is applied wrongly with the start call.

How you can verify if this is the case.

On your home assistant server go to the following directory:
/usr/local/lib/python3.8/site-packages/gardena/devices/

Open the file mower.py

Loog for the functions "self.smart_system.call_smart_system_service(self.id, data)" and replace it by "self.smart_system.call_smart_system_service(self.mower_id, data)"

After a reboot of your home assistant server, the control will work.

Or you can reinstall this gardena library to the latest version and then this should be fixed.

**Comment by ronbrou** [comment]
I had also the 502 error, but when updated to v0.2.1b3 it worked fine.
No more 502 errors and the mower responded to the commands.
Then there was an update to the newest v0.2.1, again the 502 errors appeared.
So i rolled back to v0.2.1.b3

**Comment by sabbatho** [comment]
@grm, i was about to message you, but i comment on this issue since it relates, exactly as ronbrou writes.

With the latest 0.2.1 i got 502 error back.
Work around for now is to install 0.2.1b3 as suggested above.

**Comment by eich0rn** [comment]
yeah. change from version 0.2.1 to 0.2.1b3 did it for me, too.

**Comment by grm** [comment]
Hello,

Sorry for the late answer. I am currently abroad with very limited access to my emails and internet !

I probably made a mistake in the lastest stable release (my plan was to promote the 0.2.1b3 to a new 0.2.1, but i probably have done it too fast).

In order  to solve the issue,  I deleted the latest release (0.2.1) and promoted the 0.2.1b3 to a stable release. It should permit everyone to make the integration work !

I'll have a deeper look on the why as soon as i have a better connection (probably beginning of september).

Sorry everyone for the issues !

**Comment by grm** [comment]
Should be fixed in 0.2.2.

Do not hesitate to re-open it if the issue persists ;)
