### ISSUE TITLE
Integration brokes with 0.117.0b3

### ISSUE THREAD

**Issue by northpower25** [py-smart-gardena/hass-gardena-smart-system#51]
After update to HA 0.117.0b3 the integration brokes and if i will delete an reactivate the integration i get the following error

Logger: custom_components.gardena_smart_system.config_flow
Source: custom_components/gardena_smart_system/config_flow.py:133
Integration: Gardena Smart System integration (documentation, issues) 
First occurred: 13:01:48 (1 occurrences) 
Last logged: 13:01:48

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ronbrou** [comment]
Integration broke afther update supervisor to 249 (HA 0.116.4).

**Comment by FlavorFx** [comment]
Same here.

**Comment by kayloehmann** [comment]
Same here.

**Comment by docbobo** [comment]
+1

**Comment by LucTs** [comment]
+1

**Comment by pdecat** [comment]
Same issue here, and it's not a matter of HA or supervisor version.

It's the Gardena API that is failing like it did earlier this year: https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5

Renewing the API key makes it work again: https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5#issuecomment-638851191

**Comment by northpower25** [comment]
> Same issue here, and it's not a matter of HA or supervisor version.
> 
> It's the Gardena API that is failing like it did earlier this year: #5
> 
> Renewing the API key makes it work again: [#5 (comment)](https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/5#issuecomment-638851191)

That’s works for me fine! Thanks for the explanation. 👍🏻

**Comment by docbobo** [comment]
Sorry, but for me it doesn't work. After deleting the integration and configuring it with  the new App ID, I  get:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 87, in start
    self.smart_system.authenticate()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 113, in authenticate
    self.token = self.oauth_session.fetch_token(
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Simultaneous logins detected.
```

**Comment by docbobo** [comment]
After a few restarts, it's working now...

**Comment by kayloehmann** [comment]
I created a new application and assigned all api's to it. After removing the integration and setting it up new, everything works fine again. I also had to sign new terms of use on the developer.cloud site.
