### ISSUE TITLE
gardena mower not available

### ISSUE THREAD

**Issue by fabsenet** [py-smart-gardena/hass-gardena-smart-system#52]
**Having the same issue? See https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/52#issuecomment-717270466 which solves it.**

I had the gardena mower running really well with node red flows to only start it, when it is not rainy and stuff but now it does not work anymore at all:

Log:
```
Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:88
First occurred: 13:13:49 (1 occurrences)
Last logged: 13:13:49
Error setting up entry for gardena_smart_system

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 88, in start
    self.smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

seems like something is not json but should be?

I see this error for at least a week now, thankfully the mower is on its standard plan.

No one else is it reporting here so chance is, it is a configuration error on my side?

**Comment by fabsenet** [comment]
I tried reinstalling the integration (had beta versions=yes, new try was beta versions=no) and also removed the still ghosted but existing entities and tried to re-add them, but now adding the mower does not get me beyond mail/password/appkey. the windows just reopens empty.

found this in the logs:

```


Logger: custom_components.gardena_smart_system.config_flow
Source: custom_components/gardena_smart_system/config_flow.py:133
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 14:53:33 (1 occurrences)
Last logged: 14:53:33
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by fabsenet** [comment]
I found the closed issue from some days ago (https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/51) and thought, its worth a try, so i renewed the app key on the gardena developer portal.

Then first I got a litte bit further, but found this error:

```
Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:87
First occurred: 15:01:40 (1 occurrences)
Last logged: 15:01:40
Error setting up entry for gardena_smart_system

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 87, in start
    self.smart_system.authenticate()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 113, in authenticate
    self.token = self.oauth_session.fetch_token(
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Simultaneous logins detected.
```

this was easy: `Simultaneous logins detected.`!

I logged out of the developer portal, restartet home assistant and finally my mower appeared again.

**So what is the take of this issue then?**

To not frustrate users, it would be great to have a better error handling with an actual message which prompts the user to renew the app key. You should at least update the readme of this repo to guide people?

**Comment by grm** [comment]
Hello,

i am not sure eto understand what was your issue... Was it an issue regarding the API which was not valid anymore ?
I think your first messages were not enough precise. I will try to display the message when we should have a json file but it is not .... I am not sure it was related to the API key, maybe renewing it solved an obscure issue on the gardena side ;)

I never encountered this issue, but i have a plan to clean the whole library to make it more evolvable, when i have some time.

**Comment by grm** [comment]
Closing the issue, glad it works.

If you still have issue, do not hesitate to reppen it !
