### ISSUE TITLE
Error setting up entry for gardena_smart_system

### ISSUE THREAD

**Issue by KoalaWerewolf** [py-smart-gardena/hass-gardena-smart-system#70]
I’m getting the same error as issue #68 

Running Gardena Smart System 0.2.3 on HA 2021.6.3. (had the same problem on 2021.6.2)

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:88
Integration: Gardena Smart System integration (documentation, issues) 
First occurred: 8:44:23 PM (1 occurrences) 
Last logged: 8:44:23 PM

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 88, in start
    self.smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by newlund** [comment]
I still get the same error. I have not changed anything in the Gardena dev portal since it worked.

This error originated from a custom integration.

Logger: custom_components.gardena_smart_system.config_flow
Source: custom_components/gardena_smart_system/config_flow.py:133
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 11:10:31 (1 occurrences)
Last logged: 11:10:31

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 167, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 138, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 117, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by newlund** [comment]
Tried 0.2.4b15, same problem.

**Comment by johnniemalm** [comment]
same problem .
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:89
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 13:58:58 (1 occurrences)
Last logged: 13:58:58

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 52, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 89, in start
    self.smart_system.authenticate()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 72, in authenticate
    self.token = self.oauth_session.fetch_token(
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 402, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Simultaneous logins detected for client[id=7d52ad0d-f4ca-4773-b75d-f30*********], user[id=585bb198-0780-4763-afd2-0f2*********, email=johnnie@*****.**}]

**Comment by KoalaWerewolf** [comment]
It’s currently working for me. 2021.6.5 with 0.2.4b14.

**Comment by johnniemalm** [comment]
change to 0.2.4b14 i am on 2021.6.5 same as you, error little different now.

Logger: homeassistant.config_entries
Source: util/async_.py:140
First occurred: 14:21:43 (1 occurrences)
Last logged: 14:21:43

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry
    await gardena_system.async_create_ws()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 107, in async_create_ws
    await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 224, in start_ws
    ws_url = await self.get_ws_url(location)
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 213, in get_ws_url
    r = session.post(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/gardena_smart_system/__init__.py, line 107: await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])

**Comment by HrMarcussen** [comment]
Have a similar issue. Running HA 2021.6.5 and Gardena 0.23. Worked fine until I update HA earlier today from 2021.04.xx:

Log Details (ERROR)
 This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:88
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 11:08:13 AM (1 occurrences)
Last logged: 11:08:13 AM

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 88, in start
    self.smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by johnniemalm** [comment]
Working now with latest 👍

**Comment by newlund** [comment]
What is the latest version? The latest I can find is 0.2.3 even if I select "show beta versions".
And I still get the same error when setting up the inteegration.

This error originated from a custom integration.

Logger: custom_components.gardena_smart_system.config_flow
Source: custom_components/gardena_smart_system/config_flow.py:133
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 7:41:37 (1 occurrences)
Last logged: 7:41:37

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 167, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 138, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 117, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by newlund** [comment]
Now finally I got it working (v0.2.3). Deleted my current application ID I've had for over a year and created a new one.
First I got some strange errors after adding the integration but after a couple of restarts it appeared with no errors,

**Comment by MikeLehnitz** [comment]
My solution to the problem: Deleting the integration in HA and HACS. Delete the API token at Husquana (Gardena) and reinstall everything. Restart each time after the Hacs and HA integration.

**Comment by grm** [comment]
Indeed, gardena messed up with he token often and they probably have with yours). I just added a better log message in the log when this issue will happen again !

Jérémie
