### ISSUE TITLE
DO NOT UPDATE TO 0.2.4b* yet

### ISSUE THREAD

**Issue by grm** [py-smart-gardena/hass-gardena-smart-system#72]
I am still working on it and everything does not work yet !

**Comment by ccorderod** [comment]
Hi @grm 

FYI, got this error on the log with 0.2.4b6:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 213, in start_ws
    r = session.post(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 118, in check_loop
    raise RuntimeError(
RuntimeError: Detected I/O inside the event loop. This is causing stability issues. Please report issue
```

**Comment by basn** [comment]
> I am still working on it and everything does not work yet !

That explains why it stopped working, i see that its no error that daily limit is reached which is a huge bonus! :)
Keep up the good things!
