### ISSUE TITLE
error on Gardena Smart System integration

### ISSUE THREAD

**Issue by bussio** [py-smart-gardena/hass-gardena-smart-system#76]
Since a few days I get the following error with this integration:

Logger: homeassistant.config_entries
Source: util/async_.py:140 
First occurred: 15:25:05 (1 occurrences) 
Last logged: 15:25:05

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry
    await gardena_system.async_create_ws()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 107, in async_create_ws
    await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 224, in start_ws
    ws_url = await self.get_ws_url(location)
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 213, in get_ws_url
    r = session.post(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/gardena_smart_system/__init__.py, line 107: await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])

**Comment by grm** [comment]
Hello,

I am.currently working on a new version and i have to change many things.
The beta versions are not currently working, i will delete them to avoid other issues.

Jeremie

**Comment by grm** [comment]
You should fall back to 2.1.3 for now.
