### ISSUE TITLE
Loop detected - user error or addon problem?

### ISSUE THREAD

**Issue by Dirtylobstar** [py-smart-gardena/hass-gardena-smart-system#77]
Addon logon fine to gardena servers and I have granted api access. However pretty much instant it shut down and throw these errors:

Error setting up entry for gardena_smart_system
21:15:14 – (ERROR) util/async_.py - message first occurred at 19:38:46 and shows up 2 times
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for gardena_smart_system doing I/O at custom_components/gardena_smart_system/__init__.py, line 107: await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])
21:15:14 – (WARNING) util/async_.py - message first occurred at 19:38:46 and shows up 2 times
Error handling request
19:46:36 – (ERROR) data_entry_flow.py

Full log:
2021-06-18 19:38:42 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration gardena_smart_system which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-06-18 19:38:46 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for gardena_smart_system doing I/O at custom_components/gardena_smart_system/__init__.py, line 107: await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])
2021-06-18 19:38:46 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for gardena_smart_system
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry
await gardena_system.async_create_ws()
File "/config/custom_components/gardena_smart_system/__init__.py", line 107, in async_create_ws
await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])
File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 224, in start_ws
ws_url = await self.get_ws_url(location)
File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 213, in get_ws_url
r = session.post(
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
return super(OAuth2Session, self).request(
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request
self.putrequest(method, url, **skips)
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
check_loop()
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/gardena_smart_system/__init__.py, line 107: await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])
2021-06-18 19:46:36 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 76, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 303, in _async_handle_step
self._progress.pop(flow.flow_id)
KeyError: '8e75a13190f74f8d830537fbb32f5f69'
2021-06-18 21:15:14 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for gardena_smart_system doing I/O at custom_components/gardena_smart_system/__init__.py, line 107: await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])
2021-06-18 21:15:14 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for gardena_smart_system
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry
await gardena_system.async_create_ws()
File "/config/custom_components/gardena_smart_system/__init__.py", line 107, in async_create_ws
await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])
File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 224, in start_ws
ws_url = await self.get_ws_url(location)
File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 213, in get_ws_url
r = session.post(
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 515, in request
return super(OAuth2Session, self).request(
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request
self.putrequest(method, url, **skips)
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
check_loop()
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/gardena_smart_system/__init__.py, line 107: await self.smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])

**Comment by grm** [comment]
Hello,

I am.currently working on a new version and i have to change many things.
The beta versions are not currently working, i will delete them to avood other issues.

You shoud fallback to version 2.1.3 meanwhile

Jeremie
