### ISSUE TITLE
Start Fails

### ISSUE THREAD

**Issue by tomatenkopp** [py-smart-gardena/hass-gardena-smart-system#79]
Good Morning,
this night the integration (version 0.23) doesn't get new values and after restart of Homeassistant it doesn't even load.
There were no changes in the environment, no updates, no restarts of any service, nothing - very strange.
Before it worked perfectly in Homeassistant 2021.6.6 in Synology Docker . Here's the log concerning the gardena integration when HASS starts, I hope this helps:

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:88
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 09:54:02 (1 occurrences)
Last logged: 09:54:02
Error setting up entry for gardena_smart_system

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 88, in start
    self.smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by hegart** [comment]
Hello.
I have the same problem.
I have tried to reinstall, but without success.

**Comment by flexstarr** [comment]
exact same here.

**Comment by jratys** [comment]
same here...

**Comment by depthchargex** [comment]
I have started to experience this issue.


2021-07-05 23:01:07 DEBUG (SyncWorker_5) [custom_components.gardena_smart_system.config_flow] Trying to connect to Gardena during setup
2021-07-05 23:01:12 ERROR (MainThread) [custom_components.gardena_smart_system.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jratys** [comment]
> I have also started to experience this issue. I haven't been able to get it working for some weeks now.
> 
Did you get it working before ? when did you start experiencing this issue ?

**Comment by depthchargex** [comment]
> > I have also started to experience this issue. I haven't been able to get it working for some weeks now.
> 
> Did you get it working before? when did you start experiencing this issue?

Had it working since earlier this year.  It broke after update 2021.6 I think.

**Comment by jacquesvzijp** [comment]
Hi 
I have exactly the same error (simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)) since yesterday but still on 2021.5.1 and did not do any updates. Btw also running on Synology Docker.
Jacques

**Comment by timn** [comment]
Same here. @grm could this be fixed by a new release? There have been a few commits here and in py-smart-gardena.

**Comment by rasssta** [comment]
Same issue for me as well. Stopped working today.

**Comment by grm** [comment]
Hello,

I ll try to have a look into it today !
Jeremie

**Comment by grm** [comment]
Hey,
could someone paste me some error messages/logs/stack trace from your system ?

I just restarted my instance, and I did not see this issue.

Jérémie

**Comment by tomatenkopp** [comment]
Hi, here's the newest log entry after restart of Homeassistant:

Last logged: 12:43:31
Error setting up entry for gardena_smart_system

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 88, in start
    self.smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by grm** [comment]
As i do not have the issue on my side, i'll probably have to make a debug version ..
Or maybe i can ship you some code to update the library in order to have more information about the issue ?

If someone feels confortable modifying the file smart_system.py to update this function *__reponse_has_errors* with this code  : 
```
    def __response_has_errors(self, response):
        if response.status_code not in (200, 202):
            try:
                r = response.json()
                if 'errors' in r:
                    msg = "{r['errors'][0]['title']} - {r['errors'][0]['detail']}"
                elif 'message' in r:
                    msg = f"{r['message']}"

                    if response.status_code == 403:
                        msg = f"{msg} (hint: did you 'Connect an API' in your Application?)"
                else:
                    msg = f"{r}"
            except JSONDecodeError:
                msg = response.content
            self.logger.error(f"{response.status_code} : {msg}")

            if response.status_code in (401, 403, 429):
                raise Exception(msg)
```

and paste me the output , it would be great ! 

Jérémie

**Comment by rasssta** [comment]
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py", line 160, in __response_has_errors
    r = response.json()
  File "/srv/homeassistant/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/gardena_smart_system/__init__.py", line 88, in start
    self.smart_system.update_locations()
  File "/srv/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/srv/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/srv/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py", line 170, in __response_has_errors
    except JSONDecodeError:
NameError: name 'JSONDecodeError' is not defined
```

**Comment by grm** [comment]
My bad, could you add : 
```
from json.decoder import JSONDecodeError
```

To the top of the files with the other imports please ?

**Comment by rasssta** [comment]
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/gardena_smart_system/__init__.py", line 88, in start
    self.smart_system.update_locations()
  File "/srv/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py", line 212, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/srv/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py", line 183, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/srv/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py", line 176, in __response_has_errors
    raise Exception(msg)
Exception: b''
```

```
Logger: gardena.smart_system
Source: /srv/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py:173
First occurred: 2:06:11 PM (1 occurrences) 
Last logged: 2:06:11 PM

401 : b''
```

**Comment by grm** [comment]
Hum, could you try to make a new application  in the gardena developer portal ( https://developer.husqvarnagroup.cloud/apps ) and reconfigure the integration with the new application credentials ?

The code 401 seems to be related to authentification !

Jérémie

**Comment by grm** [comment]
Or at least check your conf in the portal.

**Comment by rasssta** [comment]
I removed it and re-created it - works! 🧐

**Comment by grm** [comment]
I think there had been some token invalidation in the gardena system. It already happened in the past.

**Comment by depthchargex** [comment]
Recreating a new API seems to have worked for me also.  Thank you.

**Comment by Jpsy** [comment]
Recreating the API does not solve the problem for me.
The error I get is `Simultaneous logins detected for client`:

    Logger: homeassistant.config_entries
    Source: custom_components/gardena_smart_system/__init__.py:87
    Integration: Gardena Smart System integration (documentation, issues)
    First occurred: 20:15:24 (2 occurrences)
    Last logged: 20:17:42
    
    Error setting up entry for gardena_smart_system
    Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
      result = await component.async_setup_entry(hass, self)  # type: ignore
    File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
      await hass.async_add_executor_job(gardena_system.start)
    File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
      result = self.fn(*self.args, **self.kwargs)
    File "/config/custom_components/gardena_smart_system/__init__.py", line 87, in start
      self.smart_system.authenticate()
    File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 113, in authenticate
      self.token = self.oauth_session.fetch_token(
    File "/usr/local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
      self._client.parse_request_body_response(r.text, scope=self.scope)
    File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
      self.token = parse_token_response(body, scope=scope)
    File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
      validate_token_parameters(params)
    File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
      raise_from_error(params.get('error'), params)
    File "/usr/local/lib/python3.8/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 402, in raise_from_error
      raise cls(**kwargs)
    oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Simultaneous logins detected for client[id=3f5a...], user[id=45a6..., email=an..@...de]

I tried multiple times and there is no other second system that would try a login with the newly created API data.

Side note:
At the same time that HA lost the connection, the Gardena App also asked me to enter my credentials again.
I have a feeling that Husqvarna is fiddling around with their OAuth2 identity provider.

**Comment by rasssta** [comment]
You need to log out with your web browser

**Comment by Jpsy** [comment]
Well, I did a restart of HA which also solved it. Strange behaviour. Thanks for your help.

**Comment by timn** [comment]
I can also confirm that the following steps worked for me:

- Log in to https://developer.husqvarnagroup.cloud/
- Delete Home Assistant app
- Create a new ID
- Edit `.storage/core.config_entries` and update `client_id` and `id` fields in `data` for the entry that has `"domain": "gardena_smart_system"`.
- Logout from developer portal
- Retart HA

Maybe the fix here could then be to catch this error and send a HA notification so it pops up prominently with clear instructions.

**Comment by Jpsy** [comment]
> ...catch this error and send a HA notification so it pops up prominently with clear instructions.

This would indeed be very helpful.

**Comment by grm** [comment]
I am not sure how to achieve a good long term solution.

I already instrumented the code to be able to know the source of the issue next time in the underlying library, but I need to check how i can send the information to hass for proper display !

Jérémie

**Comment by grm** [comment]
(i can easily log at startup the issue, but alerting the front with a toaster, i am not sure)

**Comment by Jpsy** [comment]
I think it would be enough to spice up the crash message in the log with a speaking explanation. When the installation of the integration fails, you already get a clearly visible warning in the Integrations page with a direct link to corresponding log entry.

**Comment by grm** [comment]
Indeed, there is no easy way to alert the front, i think we wll have to stic to the logs (which is by the way the first thing to do when there is an issue :D )

**Comment by grm** [comment]
A new release 0.8.2 should solve the issue by printing a log when there is a token issue !
I cannot detect a wrong token from an expired token, so the message is generic ..
See https://github.com/py-smart-gardena/hass-gardena-smart-system/commit/c964c110e8f7ebe3aefa8178fd2230e31afd1f89 with a typo i will correct !

**Comment by timn** [comment]
I was thinking along the lines of a [persistent notification](https://www.home-assistant.io/integrations/persistent_notification/). Pretty much like you see new integration discoveries. Can this be sent from the plugin for this error?
