### ISSUE TITLE
no more integration after update 2021.7.0

### ISSUE THREAD

**Issue by ronbrou** [py-smart-gardena/hass-gardena-smart-system#81]
After update to HA 2021.7.0 integration does not work anymore.
I deleted de integration in HA en then uninstalled in HACS Gardena Smart System.
Installed Gardena Smart System in HACS again.
Now I cant find no Gardena Smart System in the HA integrations

**Comment by grm** [comment]
Indeed, they have upated request and its breaking change !

I will probably release a new version only for ha >-= 2021.7 !

great news !

Jérémie

**Comment by grm** [comment]
SHould be fixed in version 0.2.5b1 !

PLease tell me if you have any issue so i can mark it as final

**Comment by ronbrou** [comment]
uninstalled Gardena Smart System from HACS.
Try to install again, but the install button does not function and I get the warning message.
"You are running Home Assistant version '2021.7.0', but this repository requires minimum version '2021.7' to be installed."

**Comment by grm** [comment]
Update the repository information manually before installing and try a reinstall please

**Comment by ronbrou** [comment]
I dont understand what you mean, I dont have an installation of Gardena Smart System anymore.
I have to ad it new, so I cant do an reinstall.

**Comment by grm** [comment]
(in the 3 dots on the integration in HACS, you have an option name 'Update information'. Could you click on this option before installing/reinstalling ?

**Comment by ronbrou** [comment]
I am sorry, but on the integrations page of HACS I have no Update Information in the 3dot menu

**Comment by grm** [comment]
on the card of the integration ?

<img width="623" alt="Screenshot 2021-07-08 at 18 00 54" src="https://user-images.githubusercontent.com/70435/124954592-88906980-e016-11eb-8b15-d4a4b1afe7fc.png">

**Comment by ronbrou** [comment]
I dont have the card anymore I did an uninstall

**Comment by sabbatho** [comment]
Hi Jérémie, thanks for all your work with this :)
Just wanted to confirm that 0.2.5b1 works for me and i have connection again :)
Thanks! :)

**Comment by ronbrou** [comment]
![image](https://user-images.githubusercontent.com/62080197/124955689-87137100-e017-11eb-9c49-41aed5a175e9.png)

**Comment by grm** [comment]
@ronbrou : try intstalling it so :)

**Comment by ronbrou** [comment]
@grm. Went back to former HA snapshot.
Updated HA and Gardena Smart System.
Now it is working again.

**Comment by grm** [comment]
Perfect ! 

Jérémie

**Comment by jorgenbosman** [comment]
The latest version works fina when hass starts. But after a few hours I got the following message and then the integration stops working:

error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x7fdfe445b340>>: on_close() takes 2 positional arguments but 4 were given

**Comment by grm** [comment]
Ok, i juste released a fix in version 0.2.5b3 that fixes this bug.

can you confirm everything is ok please ?

TIA,

Jérémie

**Comment by jorgenbosman** [comment]
Installed it last night and so far the error has not occured anymore :-)

**Comment by malkie-hass** [comment]
I also had issues and found this. I´m running core-2021.7.3
I removed the integration, uninstalled and installed the latest version 0.2.5b3
When I add the Integration and fill the fields i click on send and the window just pops up again empty.

From the logs:

2021-07-17 00:09:24 ERROR (MainThread) [custom_components.gardena_smart_system.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
smart_system.update_locations()
File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 217, in update_locations
response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 188, in __call_smart_system_get
if self.__response_has_errors(response):
File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 162, in __response_has_errors
r = response.json()
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-07-17 00:10:45 ERROR (MainThread) [custom_components.gardena_smart_system.config_flow] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
smart_system.update_locations()
File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 217, in update_locations
response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 188, in __call_smart_system_get
if self.__response_has_errors(response):
File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 162, in __response_has_errors
r = response.json()
File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any idea?

**Comment by phantomski77** [comment]
Most of the time this integration failed for me in the last few updates, re-generating application key on [Husqvarna Group Cloud - Developer Portal](https://developer.husqvarnagroup.cloud) and then re-installing HACS integration usually helped to resolve the issue. I'm not sure what exactly makes the API token invalid / expire (might be a subtly different call from Home Assistant), but it does expire.

**Comment by sorcer83** [comment]
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Getting the integration installed through HACS, but when entering username, password and application key it just returns to the same form. 

I'm getting this error in the logs.

**Comment by malkie-hass** [comment]
Okay, I now recreated the api key and got further. It does the setup but than gives me a new error:

File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry
await hass.async_add_executor_job(gardena_system.start)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/gardena_smart_system/__init__.py", line 90, in start
self.smart_system.authenticate()
File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 115, in authenticate
self.token = self.oauth_session.fetch_token(
File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
self._client.parse_request_body_response(r.text, scope=self.scope)
File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
self.token = parse_token_response(body, scope=scope)
File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
validate_token_parameters(params)
File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
raise_from_error(params.get('error'), params)
File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 402, in raise_from_error
raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Simultaneous logins detected for client[id=myid], user[id=myotherid, email=my-email@email.com}]

SO what I understand is that it is already in use. I´m using the App from my Phone as well as from my wifes phone. So you can login more. Worked before as well. Any idea? I looked on https://developer.husqvarnagroup.cloud/apps but could nowhere find to disconnect. Api key was as I said recreated several times. allways same result.

Malkie

**Comment by phantomski77** [comment]
> Okay, I now recreated the api key and got further. It does the setup but than gives me a new error:
...
> SO what I understand is that it is already in use. I´m using the App from my Phone as well as from my wifes phone. So you can login more. Worked before as well. Any idea? I looked on https://developer.husqvarnagroup.cloud/apps but could nowhere find to disconnect. Api key was as I said recreated several times. allways same result.
> 
> Malkie

Try:
- [Configure/Integrations](https://my.home-assistant.io/redirect/integrations/) in your Home Assistant instance and delete Gardena Smart System *core* integration
- Recreate an API key in [Husqvarna Group Cloud - Developer portal](https://developer.husqvarnagroup.cloud/)
- Then Add Gardena Smart System *core* integration again. Enter new credentials. Restart Core.

If it doesn't help, try with extra HACS steps:
- HACS/Integrations - uninstall Gardena Smart System *HACS* Integration
- restart Core, install *HACS* Integration again
- add Gardena Smart System *core* integration again, enter credentials, restart Core.

**Comment by malkie-hass** [comment]
Hey,
thanks a lot. Got it working. Actually the only thing needed was after the integration to have a reboot.
It came up again with the same error but after reboot it worked.

Malkie

**Comment by phantomski77** [comment]
Can confirm 0.2.5b3 fixes the issue with broken feedback and also there are no error messages. All working now. Thanks @grm !

**Comment by grm** [comment]
Great !

I close the issue, felle free to reopen it if needed !

Jérémie
