### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by frankvandenhurk** [py-smart-gardena/hass-gardena-smart-system#82]
Hi,

My Gardena Smart System stopped bing connected with HomeAssistant a few days ago. I remove the integration completely and reinstalled (HACS), but when I try to annd the integration to HA and enter my crendetials I get this:

2021-07-11 18:56:39 ERROR (MainThread) [custom_components.gardena_smart_system.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.8/site-packages/gardena/smart_system.py", line 159, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Any clue of what's wrong? User error or something else?

**Comment by grm** [comment]
Hello,

Uou should find what you need there : https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/79#issuecomment-875552612

Basically you need to recreate the application in the gardena portal and then reconfigure the integration with you new token !

Jeremie

**Comment by frankvandenhurk** [comment]
Tnx for your quick reply, sorry that I didn't check the closed issues to find the solution myself.
