### ISSUE TITLE
no more integration after update 2021.8.4

### ISSUE THREAD

**Issue by ingeniumdesign** [py-smart-gardena/hass-gardena-smart-system#85]
Hi all,
i install the gardena-smart-system in HACS.
And restart the Core.

i found the Plugin in "integrations" => "add integrations" => Gardena Smart System integrations
The Popup with Input: E-Mail, Password, Application key comming.

after i push the button "Submit", the Popup comming again.

Home-Assistant-Log:
```
2021-08-09 17:26:36 DEBUG (SyncWorker_0) [custom_components.gardena_smart_system.config_flow] Trying to connect to Gardena during setup
2021-08-09 17:26:36 ERROR (SyncWorker_0) [gardena.smart_system] 403 : Forbidden (hint: did you 'Connect an API' in your Application?)
2021-08-09 17:26:36 ERROR (MainThread) [custom_components.gardena_smart_system.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 209, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 180, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 173, in __response_has_errors
    raise Exception(msg)
Exception: Forbidden (hint: did you 'Connect an API' in your Application?)
```

i hope you can fix it. thanks!

**Comment by zkiifreak** [comment]
I've got this as well:

`
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0),
    return self.scan_once(s, idx=_w(s, idx).end()),
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode,
    obj, end = self.raw_decode(s),
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode,
2021-08-09 19:54:44 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for gardena_smart_system,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup,
  File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run,
    await hass.async_add_executor_job(gardena_system.start),
    result = self.fn(*self.args, **self.kwargs),
    self.smart_system.update_locations(),
  File "/config/custom_components/gardena_smart_system/__init__.py", line 91, in start,
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 217, in update_locations,
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations"),
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 188, in __call_smart_system_get,
    if self.__response_has_errors(response):,
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 162, in __response_has_errors,
    r = response.json(),
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json,
    return complexjson.loads(self.text, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads,
    return _default_decoder.decode(s)`

**Comment by jborup** [comment]
Maybe the same as I tried earlier on and wrote here: https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/86#issuecomment-895497530

**Comment by ingeniumdesign** [comment]
i connect all 3 "Connected APIs" and now it works

**Comment by vandenbogerd** [comment]
Same issue here, even after recreating an app, with all 3 API's...

**Comment by VeniceNerd** [comment]
I have the same issue. I enter the Gardena email, the gardena password and the Application Key (it doesn't even ask for the Application secret) but when I click "submit" the all the fields just reset themselves. What could I be doing wrong?

**Comment by Paul-Vdp** [comment]
Maybe not making the effort of going through the other outstanding issues (where you would find the solution to your problem) ?

**Comment by grm** [comment]
Hello,

there has been a lot of changes reecently in the library.
Could you give it another shot please and recreate a ticket if you still have an issue ?

Thx
