### ISSUE TITLE
Not working in 2021.8.4

### ISSUE THREAD

**Issue by zkiifreak** [py-smart-gardena/hass-gardena-smart-system#86]
I get this in 2018.8[.4].
Worked before upgrade.
```
2021-08-09 19:54:44 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for gardena_smart_system,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup,
    result = await component.async_setup_entry(hass, self)  # type: ignore,
  File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry,
    await hass.async_add_executor_job(gardena_system.start),
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run,
    result = self.fn(*self.args, **self.kwargs),
  File "/config/custom_components/gardena_smart_system/__init__.py", line 91, in start,
    self.smart_system.update_locations(),
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 217, in update_locations,
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations"),
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 188, in __call_smart_system_get,
    if self.__response_has_errors(response):,
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 162, in __response_has_errors,
    r = response.json(),
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json,
    return complexjson.loads(self.text, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads,
    return _default_decoder.decode(s),
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode,
    obj, end = self.raw_decode(s),
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode,
    return self.scan_once(s, idx=_w(s, idx).end()),
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0),

```

I've updated with the latest available downloadable code from the repo.

**Comment by jborup** [comment]
@zkiifreak I have had a similar issue before. In my case it was actually the API key that got "stalled" so I suggest creating a new API key and use that one.

 You do not need to delete the old one if it is used for other things.
 
 Hope that works out for you.

**Comment by ingeniumdesign** [comment]
ohh, i connect in the API all 3 "Connected APIs".
And now it works.

**Comment by zkiifreak** [comment]
> @zkiifreak I have had a similar issue before. In my case it was actually the API key that got "stalled" so I suggest creating a new API key and use that one.
> 
> You do not need to delete the old one if it is used for other things.
> 
> Hope that works out for you.

Tried that - did not work :(
It comes back when adding the integration and states that it successfully added configuration for ''. (Kinda empty) Also related to the line in the log:
```Error setting up entry  for gardena_smart_system,```
where you'll notice the double space between entry and for...
I even tried adding all three APIs but no dice.
Any other takes? Or am I SOL?
