### ISSUE TITLE
Integration not working even after new API keys for all 3 APIs

### ISSUE THREAD

**Issue by northalpha** [py-smart-gardena/hass-gardena-smart-system#90]
I do have this issue:

```
Logger: websocket
Source: /usr/local/lib/python3.9/site-packages/websocket/_logging.py:65
First occurred: 25. August 2021, 11:06:06 (2 occurrences)
Last logged: 25. August 2021, 11:06:06

error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x7f0f8965d9d0>>: on_open() takes 1 positional argument but 2 were given
error from callback <bound method Client.on_error of <gardena.smart_system.Client object at 0x7f0f8965d9d0>>: on_error() takes 2 positional arguments but 3 were given
```

Detailed Log:

```
2021-08-25 11:06:06 ERROR (Thread-5) [websocket] error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x7f0f8965d9d0>>: on_open() takes 1 positional argument but 2 were given
2021-08-25 11:06:06 ERROR (Thread-5) [websocket] error from callback <bound method Client.on_error of <gardena.smart_system.Client object at 0x7f0f8965d9d0>>: on_error() takes 2 positional arguments but 3 were given
2021-08-25 11:06:06 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 407, in _callback
callback(self, *args)
TypeError: on_open() takes 1 positional argument but 2 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 322, in run_forever
self._callback(self.on_open)
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 412, in _callback
self.on_error(self, e)
TypeError: on_error() takes 2 positional arguments but 3 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 407, in _callback
callback(self, *args)
TypeError: on_error() takes 2 positional arguments but 3 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 371, in run_forever
self._callback(self.on_error, e)
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 412, in _callback
self.on_error(self, e)
TypeError: on_error() takes 2 positional arguments but 3 were given
```

**Comment by seb-5x** [comment]
https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/88#issuecomment-896811368

**Comment by northalpha** [comment]
Can confirm using `0.2.5b3` beta is solving this issue. thanks for the heads-up @seb-5x
