### ISSUE TITLE
New error after updating to HA core-2021.11.1

### ISSUE THREAD

**Issue by awirtz** [py-smart-gardena/hass-gardena-smart-system#93]
Hi,

running v0.2.5b3 but this new error below has freshly appeared, killing the integration for the time being.

Thanks and kind regards
Alexander

```
2021-11-05 17:32:52 DEBUG (MainThread) [custom_components.gardena_smart_system] Setting up Gardena Smart System component
2021-11-05 17:32:52 DEBUG (SyncWorker_2) [custom_components.gardena_smart_system] Starting GardenaSmartSystem
2021-11-05 17:32:53 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 91, in start
    self.smart_system.update_locations()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 217, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 188, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 162, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by northpower25** [comment]
The same here!

**Comment by unsign** [comment]
Hey guys,

I've just had exactly the same problem. After some research I found the following issue: https://github.com/py-smart-gardena/py-smart-gardena/issues/87

The following makes absolutely no sense, but fixed the issue for me: As I did NOT wanted to create a new application key, I simply went to the gardena dev portal and removed and reconnected the APIs on the existing application key. Restart Home Assistant and the magic happend -> it's working again ;)
As I said, it makes no sense, but maybe it will also help on your system ;)

Cheers,

**Comment by leonardpitzu** [comment]
@unsign thanks, worked as well in my case.

**Comment by awirtz** [comment]
Same here, removing and reconnecting the API kills the error.

Thanks @unsign!

**Comment by FlavorFx** [comment]
@unsign thanks for this hint. I have done the same and  it works properly.
