### ISSUE TITLE
Integration is Broken after update to core-2021.11.1

### ISSUE THREAD

**Issue by eich0rn** [py-smart-gardena/hass-gardena-smart-system#94]
After Update to Core 2021.11.1 the integration does not start.
Environment Information:
Core Version 2021.11.1
Supervisor 2021.10.8
Python Version: 3.9.7
Home Assistant OS 6.6
Installed AddOns:
File editor (5.3.3), Samba share (9.3.0), Log Viewer (0.12.0), HomeMatic CCU (11.3.0), Terminal & SSH (9.2.1), Emulated HUE (0.2.10)

Error Log:
Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:91
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 09:49:48 (1 occurrences)
Last logged: 09:49:48

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 53, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 91, in start
    self.smart_system.update_locations()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 217, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 188, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 162, in __response_has_errors
    r = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rostikk80** [comment]
Same issue here

**Comment by bussio** [comment]
The problem also occurs here with me.

**Comment by awirtz** [comment]
Hi,

I think this is the same as my report  #93, where it was about disconnecting and reconnecting the API in the Husqvarna developer environment. No need to reissue the API keys, worked for me without it.

Best
Alexander

**Comment by MoritzBuetzer** [comment]
Thanks @awirtz, that worked for me!

**Comment by rostikk80** [comment]
Worked for me as well!

**Comment by Azadk** [comment]
You are my hero @awirtz !

**Comment by grm** [comment]
Hello, 

Thx Arwiz for the update on the tip.
It happens sometimes, not at the same time, but by batch of people.

I will try to find the time to update the documention with this information ... it may help
