### ISSUE TITLE
2021.12 - implements device_state_attributes

### ISSUE THREAD

**Issue by LucTs** [py-smart-gardena/hass-gardena-smart-system#96]
Hi,

I´m receiving below error messages since I upgraded to HA 2021.12.

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 08:59:25 (6 occurrences)
Last logged: 08:59:25

    Entity sensor.feuchtigkeitsensor_soil_humidity (<class 'custom_components.gardena_smart_system.sensor.GardenaSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.feuchtigkeitsensor_battery_level (<class 'custom_components.gardena_smart_system.sensor.GardenaSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity sensor.gartenbewasserung_battery_level (<class 'custom_components.gardena_smart_system.sensor.GardenaSensor'>) implements device_state_attributes. Please report it to the custom component author.
    Entity switch.gartenbewasserung (<class 'custom_components.gardena_smart_system.switch.GardenaSmartWaterControl'>) implements device_state_attributes. Please report it to the custom component author.
    Entity switch.pumpe (<class 'custom_components.gardena_smart_system.switch.GardenaPowerSocket'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by kingzize** [comment]
My integration is also broken since upgrading to 2021.12

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:87
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 12:43:43 (1 occurrences)
Last logged: 12:43:43

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 87, in start
    self.smart_system.authenticate()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 113, in authenticate
    self.token = self.oauth_session.fetch_token(
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 402, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) The provided access grant is invalid, expired, or revoked.

**Comment by unsign** [comment]
Hi @LucTs 

if you're using HACS, navigate to HACS, Integrations, click the 3 dots on the "Gardena Smart System" card, then "Redownload". In the popup, choose "master" in the "Select version"-dropdown ... Then "DOWNLOAD", restart HA, and you should be done :) ... (maybe it needs a second HA-restart - don't ask me why ;))

Hope that helps :)

cheers,

**Comment by rasssta** [comment]
I have the same issue. I tried the workaround by re-downloading master and restarting twice but that didn't work.

The proper way to handle new features is by releasing a new version, one should not be forced to download the master branch.

**Comment by unsign** [comment]
> I have the same issue. I tried the workaround by re-downloading master and restarting twice but that didn't work.
> 
> The proper way to handle new features is by releasing a new version, one should not be forced to download the master branch.

Hi @rasssta

you're absolutely right ;) ... I'm also just a user who's looking for fixes/workarounds. And I'm absolutely with you, the proper way would be to release a new version, then such workarounds won't be needed :) ... @grm is there maybe a comment from your side? :) ... May we can help you maintaining this repo?

**Comment by grm** [comment]
Ok, I'll release a new version tomorrow.
The issue I have today is that depending on installation (docker, directly
from pip, ...), a required library has breaking changes that make it
incompatible.
I am planning on rewriting everything to not be dependent on this library
but did not find the time yet :)

I'll do a new release tomorrow !

Thanks for the report

**Comment by grm** [comment]
Before releasing a new version.  You are using the beta version ?
Or the main version ? (they are not using the same implementation of the faulty lib)

**Comment by rasssta** [comment]
I'm using the main version. Not sure who the question was directed to? :)

**Comment by unsign** [comment]
@grm I'm using the master branch

**Comment by nordic-style** [comment]
@grm will you release a new stable version? That would be nice.

**Comment by grm** [comment]
Resolved in v2.x — the integration was completely rewritten and no longer uses the deprecated `device_state_attributes`. Please upgrade to v2.x. Closing as resolved.
