### ISSUE TITLE
Can't load in 2022.2.5

### ISSUE THREAD

**Issue by enoch85** [py-smart-gardena/hass-gardena-smart-system#98]
```
Version | core-2022.2.5
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.91
CPU Architecture | x86_64
Timezone | Europe/Stockholm
```

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:87
Integration: Gardena Smart System integration (documentation, issues)
First occurred: 21:31:33 (1 occurrences)
Last logged: 21:31:33

```
Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 87, in start
    self.smart_system.authenticate()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 113, in authenticate
    self.token = self.oauth_session.fetch_token(
  File "/usr/local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 366, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 448, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Simultaneous logins detected for client[id=3e5834ff-a161-47df-9e43-fb4e8afa2564], user[id=8b922c9f-1971-4c36-b49d-77011a2b543c, email=daniel@danielhansson.nu}]
```

**Comment by nordic-style** [comment]
Afaik you just need to logout from the Gardena webinterface.

**Comment by cpatscheider** [comment]
I had the same error. Logging out of the Gardena webinterface did remove the error.

**Comment by grm** [comment]
Indeed, it seems you have an authentication problem ... try to logout/login and or unisintall and reinstall the component, it ay help !
You may also try to create a new application and delete the old one in the gardena web interface.

Do not hesitate to close the issue if it is working

**Comment by enoch85** [comment]
Just tested, now I can't even install and noticed it's no longer maintained, so I'm not sure if this even should be open or not.

Are there any replacement integration?

**Comment by f00dagi** [comment]
@enoch85: I seem to have the same issue, installed through HACS but cannot find it in configuration > integration. Did you find a solution or an alternative integration? Thanks.

**Comment by enoch85** [comment]
I can find the integration, but it doesn't connect, triple-checked everything.

Seems this project is dead. Sad. :(

**Comment by grm** [comment]
Too bad, you could give it another try please ?

**Comment by grm** [comment]
This was a v1.x issue. The integration has been completely rewritten in v2.x with a new authentication system. Please upgrade to v2.x. Closing as resolved.
